FROM python:3.10-slim

WORKDIR /app

RUN pip install fastapi uvicorn requests numpy

COPY app/router.py .
COPY requirements.txt .

RUN pip install -r requirements.txt

EXPOSE 9000

CMD ["uvicorn", "router:app", "--host", "0.0.0.0", "--port", "9000"]
