FROM python:3.10-slim
ENV PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
WORKDIR /app
COPY requirements.txt .
COPY agnews_20k_texts.json .
RUN pip install -r requirements.txt
RUN python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"
COPY app/router.py .
EXPOSE 9000
CMD ["uvicorn", "router:app", "--host", "0.0.0.0", "--port", "9000"]
